# Generated by Django 2.2 on 2022-07-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirana_app', '0003_auto_20220704_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
